site_name: LibSV Docs
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.highlight
plugins:
  - search